apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgA830A6rrb+A6n9rfLckOiyPGZTAN4vzx+pWtK67mHdT6cjqBn5Qv/mPrqUcE6nPa7vRJLKMqKZ94nJEjQsQGPp5FS1YloLi0q32kqvjFozd5XBs3vjPnwTbWEdUXf0B7KW7404pd6JqbkP+zWJBYhTBSgDMXHX1dh060pCJkwfv1Dz4KTacihY3lj/J8phPWnKH2MU9ymUEVrGRTllJWwf4vOR90tDE/Zzk/Mbp8wSDD5Ew78n+vLURp0DU4MGUWYHnssm1LnJ/nB6SWdhp/8mfeMrPO9wZZNxrT8uvt2i+eyYlojTboreOvRCCueij/LFn/2LRg0k1WP5phrI3n47h8I0hXSMcxpKGcyaOmZtXGIvHNHbhkP9d56c4DSTlL+FT4HDUUsZDKfYTHaeED55pV+jSm7ZpaO9Mf8lMylfT82w4zWcrecd7ikSe9i7Fmb6WEBELA9UqrO14YOyyBILTB8GjW1GQPQMkXjPsWMnfSa/vGXoEfxMQ5TZrg8mh8OKOconw4CiPTZdumsTJfluc2A+bCdC39YxClDvqw8nyaUWunYSaJJNfVlMiUoB9nvgD+7zqlh8nvJ4Np+3I827d7CHgkN7yVYFg6+XW+pwU0SLzLSvuObXQJQ42b/ksr+dO5P5o3XlPFKfKh9e+J/mXq0ZoOeOAOKktAPh9EU2R1ybusiAnhGQ2XOE/cYCkk+f3WXxsYzCuhkCga92w0aXVXxFyVdlkX/XWs11i2GTO3yVTGKswV7fDAAZe0uNT5W2G+HWDFg9cuK4cd6ElFOu0VOZi6FThIO3ikPhiT/0DoOrlCyBJHdfO3rrMah5mfj8198hH0R4WEugESuAEf6aVoHWIz4tuX8au/96YS+JYyr9mV4shvAVb9Rnrzv4+6YOQAoLLqZVo3yAtV9FGaety6HMXIj6/IfqQ/HTRvsZhOH4eoco5IGHkIkAQN7dJ8E5WK32F5+tF+NphWuD64qJ9sy4vmNW+zu9mGIIBBpE97QKr06BOkc8BMZfR0ZhLMTbS1IOK2dCJHoU7zzxG8hoJnxec/LQkFI7xbAl68B0lIIwfw9/7Qovi1ilIQqQEwzHYNKJ1AN19Yi4fNAbWZ9xjMQeyKcP6r+ttqMHdFhxDjMDDRoC2i4WvoZ4bp+En7icpcFrCmvN0c4Itr5ESJma5nTH/Z7M6h6l0JSDK5lYZ9HZVX68/JtUCyxsCV3nEMTS+gLhDlHEZubBr7r4ayP3IGBlhaGq/1Yp5lUALzGUBdchfmyJzJ49ms5xkK5NPFm94Q1sBFs0313KqRpQsWObn9bspQA6zF8h3GXCi4fTui9GMGdgY5hwFb4o53SLjL4B
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

