apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4i-assets-ibm-assetrepo-instance
spec:
  destination:
    namespace: cp4i-assets
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/cp4i-assets/ibm-assetrepo-instance
    repoURL: https://github.com/awasthan/gitops-test-cp4i-assetrepo-5
    targetRevision: main
    helm:
      releaseName: ibm-assetrepo-instance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
